name: ci

# Build and run all tests.
# - Triggers: All pushes and pull requests on any branch.
# - Runs on: All repositories (including forks)

on:
  push:
    branches: ['**']

  pull_request:
    branches: ['**']

  workflow_dispatch:  # Allows manual dispatch

# Prevents overlapping runs of this workflow on the same branch.
#   If multiple commits are pushed in quick succession, only the most recent run will complete.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Install tools
        shell: pwsh
        run: |
          Install-Module InvokeBuild -Force

      - name: Build
        shell: pwsh
        env:
          TARGET_ARCH: amd64
        run: |
          Invoke-Build

      - name: Test
        shell: pwsh
        env:
          TARGET_ARCH: amd64
        run: |
          Invoke-Build Test

      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ci-logs-${{ github.run_id }}
          path: generated/logs
          retention-days: 7  # Short log retention for CI runs
