name: publish

# Build, test and publish official Docker images.
# - Triggers: Pushes to master and scheduled weekly runs.
# - Runs on: Only the official repository (FirebirdSQL/firebird-docker)

on:
  push:
    branches:
      - master

  schedule:
    - cron: "0 0 * * 1"  # Every Monday at midnight

  workflow_dispatch:  # Allows manual dispatch

# Only a single instance of this workflow can be in execution at a given time.
concurrency:
  group: ${{ github.workflow }}

jobs:
  build-and-push-arch:
    if: ${{ github.repository == 'FirebirdSQL/firebird-docker' }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            platform: linux/amd64
            runner: ubuntu-latest
          - arch: arm64
            platform: linux/arm64
            runner: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Install tools
        shell: pwsh
        run: |
          Install-Module InvokeBuild -Force

      - name: Build
        shell: pwsh
        env:
          TARGET_ARCH: ${{ matrix.arch }}
          TARGET_PLATFORM: ${{ matrix.platform }}
        run: |
          Invoke-Build Build

      - name: Test
        shell: pwsh
        env:
          TARGET_ARCH: ${{ matrix.arch }}
        run: |
          Invoke-Build Test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish Arch Specific Image
        shell: pwsh
        env:
          TARGET_ARCH: ${{ matrix.arch }}
        run: |
          Invoke-Build PublishArchSpecificImage

      - name: Log out from Docker Hub
        run: |
          docker logout

      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: publish-logs-${{ matrix.arch }}-${{ github.run_id }}
          path: generated/logs
          retention-days: 30  # Longer log retention for published images

  create-and-push-manifests:
    needs: build-and-push-arch
    if: ${{ github.repository == 'FirebirdSQL/firebird-docker' && success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        shell: pwsh
        run: |
          Install-Module InvokeBuild -Force

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create and Push Manifests
        shell: pwsh
        run: |
          Invoke-Build CreateManifests

      - name: Log out from Docker Hub
        run: |
          docker logout
